name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: tomjfiset/er-301-am335x-build-env:1.1.0
      options: --platform=linux/amd64

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout Submodules
      run: git submodule update --init --recursive

    - name: Build Release
      run: make -j all ARCH=am335x PROFILE=release
